Update links to 18F Pages sites to their new 18f.gov subdomain URLs
18F/archived-guides pull request #53
Opened 2017-05-22 16:09 UTC by jseppi

This PR updates all `pages.18f.gov/<PAGE>` links in this repo's content to their new URLs of the form `<PAGE>.18f.gov`.

In addition, it 
- Removes the link to [Development Environment Guide](https://pages.18f.gov/dev-environment/) because that guide will not be migrated and will thus soon be taken down.
- Adds the `author` config to `_config.yml` in order to fix the missing content in the footer of the site.

2017-05-22 16:09 UTC, jseppi commented
@wslack I marked you as the reviewer, but if it should be someone else, please let me know.

2017-05-22 22:01 UTC, wslack requested changes
Let's add these please:

https://plain-language-tutorial.18f.gov
https://lean-product-design.18f.gov/
https://contracting-cookbook.18f.gov/
https://digital-acquisition-playbook.18f.gov/
http://modularcontracting.18f.gov/
https://design-principles-guide.18f.gov


Testing Cookbook needs to be reordered.

2017-05-22 23:07 UTC, jseppi commented
Thanks for the review, @wslack. Changes made!

2017-05-23 04:10 UTC, wslack approved these changes

2017-05-23 04:10 UTC, wslack commented
https://federalist.fr.cloud.gov/preview/18f/guides/update-links/ looks great. Merging.

2017-05-23 04:10 UTC, merged